
import pandas as pd
#Reading CSV files (e.g. a table generated by excel)
df = pd.read_csv('data.csv')    #becomes a dataframe.
#print(df)                      #it won't print the entire thing (only first and last 5 rows) unless we print(data.to_string()) 
#We can also specify data.head() or data.tail() so it prints the specific no. of rows passed (if none it defaults to 5)


#Reading JSON files
df = pd.read_json('data.json')  #csv looks nicer, has a better format and excel understands it.
#print(df.to_string())


